/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddressValidity model module.
 * @module model/AddressValidity
 * @version 4.0.14
 */
class AddressValidity {
    /**
     * Constructs a new <code>AddressValidity</code>.
     * Validity status of Ergo address
     * @alias module:model/AddressValidity
     * @param address {String} Encoded Ergo Address
     * @param isValid {Boolean} 
     */
    constructor(address, isValid) { 
        
        AddressValidity.initialize(this, address, isValid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, isValid) { 
        obj['address'] = address;
        obj['isValid'] = isValid;
    }

    /**
     * Constructs a <code>AddressValidity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressValidity} obj Optional instance to populate.
     * @return {module:model/AddressValidity} The populated <code>AddressValidity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressValidity();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('isValid')) {
                obj['isValid'] = ApiClient.convertToType(data['isValid'], 'Boolean');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Encoded Ergo Address
 * @member {String} address
 */
AddressValidity.prototype['address'] = undefined;

/**
 * @member {Boolean} isValid
 */
AddressValidity.prototype['isValid'] = undefined;

/**
 * @member {String} error
 */
AddressValidity.prototype['error'] = undefined;






export default AddressValidity;

