/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScanningPredicate from './ScanningPredicate';

/**
 * The AndPredicateAllOf model module.
 * @module model/AndPredicateAllOf
 * @version 4.0.14
 */
class AndPredicateAllOf {
    /**
     * Constructs a new <code>AndPredicateAllOf</code>.
     * @alias module:model/AndPredicateAllOf
     */
    constructor() { 
        
        AndPredicateAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AndPredicateAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AndPredicateAllOf} obj Optional instance to populate.
     * @return {module:model/AndPredicateAllOf} The populated <code>AndPredicateAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AndPredicateAllOf();

            if (data.hasOwnProperty('args')) {
                obj['args'] = ApiClient.convertToType(data['args'], [ScanningPredicate]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ScanningPredicate>} args
 */
AndPredicateAllOf.prototype['args'] = undefined;






export default AndPredicateAllOf;

