/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AvlTreeData model module.
 * @module model/AvlTreeData
 * @version 4.0.14
 */
class AvlTreeData {
    /**
     * Constructs a new <code>AvlTreeData</code>.
     * @alias module:model/AvlTreeData
     * @param digest {String} Base16-encoded 32 byte digest
     */
    constructor(digest) { 
        
        AvlTreeData.initialize(this, digest);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, digest) { 
        obj['digest'] = digest;
    }

    /**
     * Constructs a <code>AvlTreeData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AvlTreeData} obj Optional instance to populate.
     * @return {module:model/AvlTreeData} The populated <code>AvlTreeData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AvlTreeData();

            if (data.hasOwnProperty('digest')) {
                obj['digest'] = ApiClient.convertToType(data['digest'], 'String');
            }
            if (data.hasOwnProperty('treeFlags')) {
                obj['treeFlags'] = ApiClient.convertToType(data['treeFlags'], 'Number');
            }
            if (data.hasOwnProperty('keyLength')) {
                obj['keyLength'] = ApiClient.convertToType(data['keyLength'], 'Number');
            }
            if (data.hasOwnProperty('valueLength')) {
                obj['valueLength'] = ApiClient.convertToType(data['valueLength'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Base16-encoded 32 byte digest
 * @member {String} digest
 */
AvlTreeData.prototype['digest'] = undefined;

/**
 * @member {Number} treeFlags
 */
AvlTreeData.prototype['treeFlags'] = undefined;

/**
 * @member {Number} keyLength
 */
AvlTreeData.prototype['keyLength'] = undefined;

/**
 * @member {Number} valueLength
 */
AvlTreeData.prototype['valueLength'] = undefined;






export default AvlTreeData;

