/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PowSolutions from './PowSolutions';

/**
 * The BlockHeader model module.
 * @module model/BlockHeader
 * @version 4.0.14
 */
class BlockHeader {
    /**
     * Constructs a new <code>BlockHeader</code>.
     * @alias module:model/BlockHeader
     * @param id {String} Base16-encoded 32 byte modifier id
     * @param timestamp {Number} Basic timestamp definition
     * @param version {Number} Ergo blockchain protocol version
     * @param adProofsRoot {String} Base16-encoded 32 byte digest
     * @param stateRoot {String} Base16-encoded 33 byte digest - digest with extra byte with tree height
     * @param transactionsRoot {String} Base16-encoded 32 byte digest
     * @param nBits {Number} 
     * @param extensionHash {String} Base16-encoded 32 byte digest
     * @param powSolutions {module:model/PowSolutions} 
     * @param height {Number} 
     * @param difficulty {Number} 
     * @param parentId {String} Base16-encoded 32 byte modifier id
     * @param votes {String} Base16-encoded votes for a soft-fork and parameters
     */
    constructor(id, timestamp, version, adProofsRoot, stateRoot, transactionsRoot, nBits, extensionHash, powSolutions, height, difficulty, parentId, votes) { 
        
        BlockHeader.initialize(this, id, timestamp, version, adProofsRoot, stateRoot, transactionsRoot, nBits, extensionHash, powSolutions, height, difficulty, parentId, votes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, timestamp, version, adProofsRoot, stateRoot, transactionsRoot, nBits, extensionHash, powSolutions, height, difficulty, parentId, votes) { 
        obj['id'] = id;
        obj['timestamp'] = timestamp;
        obj['version'] = version;
        obj['adProofsRoot'] = adProofsRoot;
        obj['stateRoot'] = stateRoot;
        obj['transactionsRoot'] = transactionsRoot;
        obj['nBits'] = nBits;
        obj['extensionHash'] = extensionHash;
        obj['powSolutions'] = powSolutions;
        obj['height'] = height;
        obj['difficulty'] = difficulty;
        obj['parentId'] = parentId;
        obj['votes'] = votes;
    }

    /**
     * Constructs a <code>BlockHeader</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockHeader} obj Optional instance to populate.
     * @return {module:model/BlockHeader} The populated <code>BlockHeader</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockHeader();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('adProofsRoot')) {
                obj['adProofsRoot'] = ApiClient.convertToType(data['adProofsRoot'], 'String');
            }
            if (data.hasOwnProperty('stateRoot')) {
                obj['stateRoot'] = ApiClient.convertToType(data['stateRoot'], 'String');
            }
            if (data.hasOwnProperty('transactionsRoot')) {
                obj['transactionsRoot'] = ApiClient.convertToType(data['transactionsRoot'], 'String');
            }
            if (data.hasOwnProperty('nBits')) {
                obj['nBits'] = ApiClient.convertToType(data['nBits'], 'Number');
            }
            if (data.hasOwnProperty('extensionHash')) {
                obj['extensionHash'] = ApiClient.convertToType(data['extensionHash'], 'String');
            }
            if (data.hasOwnProperty('powSolutions')) {
                obj['powSolutions'] = PowSolutions.constructFromObject(data['powSolutions']);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('difficulty')) {
                obj['difficulty'] = ApiClient.convertToType(data['difficulty'], 'Number');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('votes')) {
                obj['votes'] = ApiClient.convertToType(data['votes'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('extensionId')) {
                obj['extensionId'] = ApiClient.convertToType(data['extensionId'], 'String');
            }
            if (data.hasOwnProperty('transactionsId')) {
                obj['transactionsId'] = ApiClient.convertToType(data['transactionsId'], 'String');
            }
            if (data.hasOwnProperty('adProofsId')) {
                obj['adProofsId'] = ApiClient.convertToType(data['adProofsId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} id
 */
BlockHeader.prototype['id'] = undefined;

/**
 * Basic timestamp definition
 * @member {Number} timestamp
 */
BlockHeader.prototype['timestamp'] = undefined;

/**
 * Ergo blockchain protocol version
 * @member {Number} version
 */
BlockHeader.prototype['version'] = undefined;

/**
 * Base16-encoded 32 byte digest
 * @member {String} adProofsRoot
 */
BlockHeader.prototype['adProofsRoot'] = undefined;

/**
 * Base16-encoded 33 byte digest - digest with extra byte with tree height
 * @member {String} stateRoot
 */
BlockHeader.prototype['stateRoot'] = undefined;

/**
 * Base16-encoded 32 byte digest
 * @member {String} transactionsRoot
 */
BlockHeader.prototype['transactionsRoot'] = undefined;

/**
 * @member {Number} nBits
 */
BlockHeader.prototype['nBits'] = undefined;

/**
 * Base16-encoded 32 byte digest
 * @member {String} extensionHash
 */
BlockHeader.prototype['extensionHash'] = undefined;

/**
 * @member {module:model/PowSolutions} powSolutions
 */
BlockHeader.prototype['powSolutions'] = undefined;

/**
 * @member {Number} height
 */
BlockHeader.prototype['height'] = undefined;

/**
 * @member {Number} difficulty
 */
BlockHeader.prototype['difficulty'] = undefined;

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} parentId
 */
BlockHeader.prototype['parentId'] = undefined;

/**
 * Base16-encoded votes for a soft-fork and parameters
 * @member {String} votes
 */
BlockHeader.prototype['votes'] = undefined;

/**
 * Size in bytes
 * @member {Number} size
 */
BlockHeader.prototype['size'] = undefined;

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} extensionId
 */
BlockHeader.prototype['extensionId'] = undefined;

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} transactionsId
 */
BlockHeader.prototype['transactionsId'] = undefined;

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} adProofsId
 */
BlockHeader.prototype['adProofsId'] = undefined;






export default BlockHeader;

