/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContainsAssetPredicateAllOf model module.
 * @module model/ContainsAssetPredicateAllOf
 * @version 4.0.14
 */
class ContainsAssetPredicateAllOf {
    /**
     * Constructs a new <code>ContainsAssetPredicateAllOf</code>.
     * @alias module:model/ContainsAssetPredicateAllOf
     */
    constructor() { 
        
        ContainsAssetPredicateAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainsAssetPredicateAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainsAssetPredicateAllOf} obj Optional instance to populate.
     * @return {module:model/ContainsAssetPredicateAllOf} The populated <code>ContainsAssetPredicateAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainsAssetPredicateAllOf();

            if (data.hasOwnProperty('assetId')) {
                obj['assetId'] = ApiClient.convertToType(data['assetId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} assetId
 */
ContainsAssetPredicateAllOf.prototype['assetId'] = undefined;






export default ContainsAssetPredicateAllOf;

