/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainsAssetPredicateAllOf from './ContainsAssetPredicateAllOf';
import ScanningPredicate from './ScanningPredicate';

/**
 * The ContainsAssetPredicate model module.
 * @module model/ContainsAssetPredicate
 * @version 4.0.14
 */
class ContainsAssetPredicate {
    /**
     * Constructs a new <code>ContainsAssetPredicate</code>.
     * @alias module:model/ContainsAssetPredicate
     * @implements module:model/ScanningPredicate
     * @implements module:model/ContainsAssetPredicateAllOf
     * @param predicate {String} 
     */
    constructor(predicate) { 
        ScanningPredicate.initialize(this, predicate);ContainsAssetPredicateAllOf.initialize(this);
        ContainsAssetPredicate.initialize(this, predicate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, predicate) { 
        obj['predicate'] = predicate;
    }

    /**
     * Constructs a <code>ContainsAssetPredicate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainsAssetPredicate} obj Optional instance to populate.
     * @return {module:model/ContainsAssetPredicate} The populated <code>ContainsAssetPredicate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainsAssetPredicate();
            ScanningPredicate.constructFromObject(data, obj);
            ContainsAssetPredicateAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('predicate')) {
                obj['predicate'] = ApiClient.convertToType(data['predicate'], 'String');
            }
            if (data.hasOwnProperty('assetId')) {
                obj['assetId'] = ApiClient.convertToType(data['assetId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} predicate
 */
ContainsAssetPredicate.prototype['predicate'] = undefined;

/**
 * @member {String} assetId
 */
ContainsAssetPredicate.prototype['assetId'] = undefined;


// Implement ScanningPredicate interface:
/**
 * @member {String} predicate
 */
ScanningPredicate.prototype['predicate'] = undefined;
// Implement ContainsAssetPredicateAllOf interface:
/**
 * @member {String} assetId
 */
ContainsAssetPredicateAllOf.prototype['assetId'] = undefined;




export default ContainsAssetPredicate;

