/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContainsPredicateAllOf model module.
 * @module model/ContainsPredicateAllOf
 * @version 4.0.14
 */
class ContainsPredicateAllOf {
    /**
     * Constructs a new <code>ContainsPredicateAllOf</code>.
     * @alias module:model/ContainsPredicateAllOf
     */
    constructor() { 
        
        ContainsPredicateAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainsPredicateAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainsPredicateAllOf} obj Optional instance to populate.
     * @return {module:model/ContainsPredicateAllOf} The populated <code>ContainsPredicateAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainsPredicateAllOf();

            if (data.hasOwnProperty('register')) {
                obj['register'] = ApiClient.convertToType(data['register'], 'String');
            }
            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} register
 */
ContainsPredicateAllOf.prototype['register'] = undefined;

/**
 * @member {String} bytes
 */
ContainsPredicateAllOf.prototype['bytes'] = undefined;






export default ContainsPredicateAllOf;

