/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SigmaBoolean from './SigmaBoolean';

/**
 * The CryptoResult model module.
 * @module model/CryptoResult
 * @version 4.0.14
 */
class CryptoResult {
    /**
     * Constructs a new <code>CryptoResult</code>.
     * Result of executeWithContext request (reduceToCrypto)
     * @alias module:model/CryptoResult
     * @param value {module:model/SigmaBoolean} 
     * @param cost {Number} Estimated cost of contract execution
     */
    constructor(value, cost) { 
        
        CryptoResult.initialize(this, value, cost);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, cost) { 
        obj['value'] = value;
        obj['cost'] = cost;
    }

    /**
     * Constructs a <code>CryptoResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CryptoResult} obj Optional instance to populate.
     * @return {module:model/CryptoResult} The populated <code>CryptoResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CryptoResult();

            if (data.hasOwnProperty('value')) {
                obj['value'] = SigmaBoolean.constructFromObject(data['value']);
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/SigmaBoolean} value
 */
CryptoResult.prototype['value'] = undefined;

/**
 * Estimated cost of contract execution
 * @member {Number} cost
 */
CryptoResult.prototype['cost'] = undefined;






export default CryptoResult;

