/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmissionInfo model module.
 * @module model/EmissionInfo
 * @version 4.0.14
 */
class EmissionInfo {
    /**
     * Constructs a new <code>EmissionInfo</code>.
     * Emission info for height
     * @alias module:model/EmissionInfo
     */
    constructor() { 
        
        EmissionInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmissionInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmissionInfo} obj Optional instance to populate.
     * @return {module:model/EmissionInfo} The populated <code>EmissionInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmissionInfo();

            if (data.hasOwnProperty('minerReward')) {
                obj['minerReward'] = ApiClient.convertToType(data['minerReward'], 'Number');
            }
            if (data.hasOwnProperty('totalCoinsIssued')) {
                obj['totalCoinsIssued'] = ApiClient.convertToType(data['totalCoinsIssued'], 'Number');
            }
            if (data.hasOwnProperty('totalRemainCoins')) {
                obj['totalRemainCoins'] = ApiClient.convertToType(data['totalRemainCoins'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} minerReward
 */
EmissionInfo.prototype['minerReward'] = undefined;

/**
 * @member {Number} totalCoinsIssued
 */
EmissionInfo.prototype['totalCoinsIssued'] = undefined;

/**
 * @member {Number} totalRemainCoins
 */
EmissionInfo.prototype['totalRemainCoins'] = undefined;






export default EmissionInfo;

