/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainsPredicateAllOf from './ContainsPredicateAllOf';
import ScanningPredicate from './ScanningPredicate';

/**
 * The EqualsPredicate model module.
 * @module model/EqualsPredicate
 * @version 4.0.14
 */
class EqualsPredicate {
    /**
     * Constructs a new <code>EqualsPredicate</code>.
     * @alias module:model/EqualsPredicate
     * @implements module:model/ScanningPredicate
     * @implements module:model/ContainsPredicateAllOf
     * @param predicate {String} 
     */
    constructor(predicate) { 
        ScanningPredicate.initialize(this, predicate);ContainsPredicateAllOf.initialize(this);
        EqualsPredicate.initialize(this, predicate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, predicate) { 
        obj['predicate'] = predicate;
    }

    /**
     * Constructs a <code>EqualsPredicate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EqualsPredicate} obj Optional instance to populate.
     * @return {module:model/EqualsPredicate} The populated <code>EqualsPredicate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EqualsPredicate();
            ScanningPredicate.constructFromObject(data, obj);
            ContainsPredicateAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('predicate')) {
                obj['predicate'] = ApiClient.convertToType(data['predicate'], 'String');
            }
            if (data.hasOwnProperty('register')) {
                obj['register'] = ApiClient.convertToType(data['register'], 'String');
            }
            if (data.hasOwnProperty('bytes')) {
                obj['bytes'] = ApiClient.convertToType(data['bytes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} predicate
 */
EqualsPredicate.prototype['predicate'] = undefined;

/**
 * @member {String} register
 */
EqualsPredicate.prototype['register'] = undefined;

/**
 * @member {String} bytes
 */
EqualsPredicate.prototype['bytes'] = undefined;


// Implement ScanningPredicate interface:
/**
 * @member {String} predicate
 */
ScanningPredicate.prototype['predicate'] = undefined;
// Implement ContainsPredicateAllOf interface:
/**
 * @member {String} register
 */
ContainsPredicateAllOf.prototype['register'] = undefined;
/**
 * @member {String} bytes
 */
ContainsPredicateAllOf.prototype['bytes'] = undefined;




export default EqualsPredicate;

