/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Extension model module.
 * @module model/Extension
 * @version 4.0.14
 */
class Extension {
    /**
     * Constructs a new <code>Extension</code>.
     * @alias module:model/Extension
     * @param headerId {String} Base16-encoded 32 byte modifier id
     * @param digest {String} Base16-encoded 32 byte digest
     * @param fields {Array.<Array.<String>>} List of key-value records
     */
    constructor(headerId, digest, fields) { 
        
        Extension.initialize(this, headerId, digest, fields);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, headerId, digest, fields) { 
        obj['headerId'] = headerId;
        obj['digest'] = digest;
        obj['fields'] = fields;
    }

    /**
     * Constructs a <code>Extension</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Extension} obj Optional instance to populate.
     * @return {module:model/Extension} The populated <code>Extension</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Extension();

            if (data.hasOwnProperty('headerId')) {
                obj['headerId'] = ApiClient.convertToType(data['headerId'], 'String');
            }
            if (data.hasOwnProperty('digest')) {
                obj['digest'] = ApiClient.convertToType(data['digest'], 'String');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [Array]);
            }
        }
        return obj;
    }


}

/**
 * Base16-encoded 32 byte modifier id
 * @member {String} headerId
 */
Extension.prototype['headerId'] = undefined;

/**
 * Base16-encoded 32 byte digest
 * @member {String} digest
 */
Extension.prototype['digest'] = undefined;

/**
 * List of key-value records
 * @member {Array.<Array.<String>>} fields
 */
Extension.prototype['fields'] = undefined;






export default Extension;

