/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeeHistogramBin model module.
 * @module model/FeeHistogramBin
 * @version 4.0.14
 */
class FeeHistogramBin {
    /**
     * Constructs a new <code>FeeHistogramBin</code>.
     * Fee histogram bin
     * @alias module:model/FeeHistogramBin
     */
    constructor() { 
        
        FeeHistogramBin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FeeHistogramBin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeeHistogramBin} obj Optional instance to populate.
     * @return {module:model/FeeHistogramBin} The populated <code>FeeHistogramBin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeeHistogramBin();

            if (data.hasOwnProperty('nTxns')) {
                obj['nTxns'] = ApiClient.convertToType(data['nTxns'], 'Number');
            }
            if (data.hasOwnProperty('totalFee')) {
                obj['totalFee'] = ApiClient.convertToType(data['totalFee'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} nTxns
 */
FeeHistogramBin.prototype['nTxns'] = undefined;

/**
 * @member {Number} totalFee
 */
FeeHistogramBin.prototype['totalFee'] = undefined;






export default FeeHistogramBin;

