/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GenerateCommitmentsRequestSecrets from './GenerateCommitmentsRequestSecrets';
import UnsignedErgoTransaction from './UnsignedErgoTransaction';

/**
 * The GenerateCommitmentsRequest model module.
 * @module model/GenerateCommitmentsRequest
 * @version 4.0.14
 */
class GenerateCommitmentsRequest {
    /**
     * Constructs a new <code>GenerateCommitmentsRequest</code>.
     * request to generate commitments to sign a transaction
     * @alias module:model/GenerateCommitmentsRequest
     * @param tx {module:model/UnsignedErgoTransaction} 
     */
    constructor(tx) { 
        
        GenerateCommitmentsRequest.initialize(this, tx);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tx) { 
        obj['tx'] = tx;
    }

    /**
     * Constructs a <code>GenerateCommitmentsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateCommitmentsRequest} obj Optional instance to populate.
     * @return {module:model/GenerateCommitmentsRequest} The populated <code>GenerateCommitmentsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateCommitmentsRequest();

            if (data.hasOwnProperty('tx')) {
                obj['tx'] = UnsignedErgoTransaction.constructFromObject(data['tx']);
            }
            if (data.hasOwnProperty('secrets')) {
                obj['secrets'] = GenerateCommitmentsRequestSecrets.constructFromObject(data['secrets']);
            }
            if (data.hasOwnProperty('inputsRaw')) {
                obj['inputsRaw'] = ApiClient.convertToType(data['inputsRaw'], ['String']);
            }
            if (data.hasOwnProperty('dataInputsRaw')) {
                obj['dataInputsRaw'] = ApiClient.convertToType(data['dataInputsRaw'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UnsignedErgoTransaction} tx
 */
GenerateCommitmentsRequest.prototype['tx'] = undefined;

/**
 * @member {module:model/GenerateCommitmentsRequestSecrets} secrets
 */
GenerateCommitmentsRequest.prototype['secrets'] = undefined;

/**
 * Optional list of inputs to be used in serialized form
 * @member {Array.<String>} inputsRaw
 */
GenerateCommitmentsRequest.prototype['inputsRaw'] = undefined;

/**
 * Optional list of inputs to be used in serialized form
 * @member {Array.<String>} dataInputsRaw
 */
GenerateCommitmentsRequest.prototype['dataInputsRaw'] = undefined;






export default GenerateCommitmentsRequest;

