/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DhtSecret from './DhtSecret';

/**
 * The GenerateCommitmentsRequestSecrets model module.
 * @module model/GenerateCommitmentsRequestSecrets
 * @version 4.0.14
 */
class GenerateCommitmentsRequestSecrets {
    /**
     * Constructs a new <code>GenerateCommitmentsRequestSecrets</code>.
     * Optionally, external secrets used for signing
     * @alias module:model/GenerateCommitmentsRequestSecrets
     */
    constructor() { 
        
        GenerateCommitmentsRequestSecrets.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateCommitmentsRequestSecrets</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateCommitmentsRequestSecrets} obj Optional instance to populate.
     * @return {module:model/GenerateCommitmentsRequestSecrets} The populated <code>GenerateCommitmentsRequestSecrets</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateCommitmentsRequestSecrets();

            if (data.hasOwnProperty('dlog')) {
                obj['dlog'] = ApiClient.convertToType(data['dlog'], ['String']);
            }
            if (data.hasOwnProperty('dht')) {
                obj['dht'] = ApiClient.convertToType(data['dht'], [DhtSecret]);
            }
        }
        return obj;
    }


}

/**
 * Sequence of secret exponents (DLOG secrets)
 * @member {Array.<String>} dlog
 */
GenerateCommitmentsRequestSecrets.prototype['dlog'] = undefined;

/**
 * Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)
 * @member {Array.<module:model/DhtSecret>} dht
 */
GenerateCommitmentsRequestSecrets.prototype['dht'] = undefined;






export default GenerateCommitmentsRequestSecrets;

