/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerkleProof model module.
 * @module model/MerkleProof
 * @version 4.0.14
 */
class MerkleProof {
    /**
     * Constructs a new <code>MerkleProof</code>.
     * Merkle proof for a leaf, which is an array of bytes (e.g. a transaction identifier)
     * @alias module:model/MerkleProof
     * @param leaf {String} Base16-encoded Merkle tree leaf bytes
     */
    constructor(leaf) { 
        
        MerkleProof.initialize(this, leaf);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, leaf) { 
        obj['leaf'] = leaf;
    }

    /**
     * Constructs a <code>MerkleProof</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerkleProof} obj Optional instance to populate.
     * @return {module:model/MerkleProof} The populated <code>MerkleProof</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerkleProof();

            if (data.hasOwnProperty('leaf')) {
                obj['leaf'] = ApiClient.convertToType(data['leaf'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Base16-encoded Merkle tree leaf bytes
 * @member {String} leaf
 */
MerkleProof.prototype['leaf'] = undefined;






export default MerkleProof;

