/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Asset from './Asset';

/**
 * The PaymentRequest model module.
 * @module model/PaymentRequest
 * @version 4.0.14
 */
class PaymentRequest {
    /**
     * Constructs a new <code>PaymentRequest</code>.
     * Request for generation of payment transaction to a given address
     * @alias module:model/PaymentRequest
     * @param address {String} Encoded Ergo Address
     * @param value {Number} Payment amount
     */
    constructor(address, value) { 
        
        PaymentRequest.initialize(this, address, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, value) { 
        obj['address'] = address;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>PaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRequest} obj Optional instance to populate.
     * @return {module:model/PaymentRequest} The populated <code>PaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRequest();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('assets')) {
                obj['assets'] = ApiClient.convertToType(data['assets'], [Asset]);
            }
            if (data.hasOwnProperty('registers')) {
                obj['registers'] = ApiClient.convertToType(data['registers'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * Encoded Ergo Address
 * @member {String} address
 */
PaymentRequest.prototype['address'] = undefined;

/**
 * Payment amount
 * @member {Number} value
 */
PaymentRequest.prototype['value'] = undefined;

/**
 * Assets list in the transaction
 * @member {Array.<module:model/Asset>} assets
 */
PaymentRequest.prototype['assets'] = undefined;

/**
 * Ergo box registers
 * @member {Object.<String, String>} registers
 */
PaymentRequest.prototype['registers'] = undefined;






export default PaymentRequest;

