/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockHeader from './BlockHeader';

/**
 * The PopowHeader model module.
 * @module model/PopowHeader
 * @version 4.0.14
 */
class PopowHeader {
    /**
     * Constructs a new <code>PopowHeader</code>.
     * @alias module:model/PopowHeader
     * @param header {module:model/BlockHeader} 
     * @param interlinks {Array.<String>} Array of header interlinks
     */
    constructor(header, interlinks) { 
        
        PopowHeader.initialize(this, header, interlinks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, header, interlinks) { 
        obj['header'] = header;
        obj['interlinks'] = interlinks;
    }

    /**
     * Constructs a <code>PopowHeader</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PopowHeader} obj Optional instance to populate.
     * @return {module:model/PopowHeader} The populated <code>PopowHeader</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PopowHeader();

            if (data.hasOwnProperty('header')) {
                obj['header'] = BlockHeader.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('interlinks')) {
                obj['interlinks'] = ApiClient.convertToType(data['interlinks'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockHeader} header
 */
PopowHeader.prototype['header'] = undefined;

/**
 * Array of header interlinks
 * @member {Array.<String>} interlinks
 */
PopowHeader.prototype['interlinks'] = undefined;






export default PopowHeader;

