/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PowSolutions model module.
 * @module model/PowSolutions
 * @version 4.0.14
 */
class PowSolutions {
    /**
     * Constructs a new <code>PowSolutions</code>.
     * An object containing all components of pow solution
     * @alias module:model/PowSolutions
     * @param pk {String} Base16-encoded public key
     * @param w {String} 
     * @param n {String} 
     * @param d {Number} 
     */
    constructor(pk, w, n, d) { 
        
        PowSolutions.initialize(this, pk, w, n, d);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pk, w, n, d) { 
        obj['pk'] = pk;
        obj['w'] = w;
        obj['n'] = n;
        obj['d'] = d;
    }

    /**
     * Constructs a <code>PowSolutions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PowSolutions} obj Optional instance to populate.
     * @return {module:model/PowSolutions} The populated <code>PowSolutions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PowSolutions();

            if (data.hasOwnProperty('pk')) {
                obj['pk'] = ApiClient.convertToType(data['pk'], 'String');
            }
            if (data.hasOwnProperty('w')) {
                obj['w'] = ApiClient.convertToType(data['w'], 'String');
            }
            if (data.hasOwnProperty('n')) {
                obj['n'] = ApiClient.convertToType(data['n'], 'String');
            }
            if (data.hasOwnProperty('d')) {
                obj['d'] = ApiClient.convertToType(data['d'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Base16-encoded public key
 * @member {String} pk
 */
PowSolutions.prototype['pk'] = undefined;

/**
 * @member {String} w
 */
PowSolutions.prototype['w'] = undefined;

/**
 * @member {String} n
 */
PowSolutions.prototype['n'] = undefined;

/**
 * @member {Number} d
 */
PowSolutions.prototype['d'] = undefined;






export default PowSolutions;

