/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErgoTransactionOutput from './ErgoTransactionOutput';

/**
 * The ScanIdsBox model module.
 * @module model/ScanIdsBox
 * @version 4.0.14
 */
class ScanIdsBox {
    /**
     * Constructs a new <code>ScanIdsBox</code>.
     * Ergo box with associated scans (their respective identifiers)
     * @alias module:model/ScanIdsBox
     * @param scanIds {Array.<Number>} 
     * @param box {module:model/ErgoTransactionOutput} 
     */
    constructor(scanIds, box) { 
        
        ScanIdsBox.initialize(this, scanIds, box);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, scanIds, box) { 
        obj['scanIds'] = scanIds;
        obj['box'] = box;
    }

    /**
     * Constructs a <code>ScanIdsBox</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScanIdsBox} obj Optional instance to populate.
     * @return {module:model/ScanIdsBox} The populated <code>ScanIdsBox</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScanIdsBox();

            if (data.hasOwnProperty('scanIds')) {
                obj['scanIds'] = ApiClient.convertToType(data['scanIds'], ['Number']);
            }
            if (data.hasOwnProperty('box')) {
                obj['box'] = ErgoTransactionOutput.constructFromObject(data['box']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} scanIds
 */
ScanIdsBox.prototype['scanIds'] = undefined;

/**
 * @member {module:model/ErgoTransactionOutput} box
 */
ScanIdsBox.prototype['box'] = undefined;






export default ScanIdsBox;

