/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SigmaBoolean model module.
 * @module model/SigmaBoolean
 * @version 4.0.14
 */
class SigmaBoolean {
    /**
     * Constructs a new <code>SigmaBoolean</code>.
     * Algebraic data type of sigma proposition expressions
     * @alias module:model/SigmaBoolean
     * @param op {Number} Sigma opCode
     */
    constructor(op) { 
        
        SigmaBoolean.initialize(this, op);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, op) { 
        obj['op'] = op;
    }

    /**
     * Constructs a <code>SigmaBoolean</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SigmaBoolean} obj Optional instance to populate.
     * @return {module:model/SigmaBoolean} The populated <code>SigmaBoolean</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SigmaBoolean();

            if (data.hasOwnProperty('op')) {
                obj['op'] = ApiClient.convertToType(data['op'], 'Number');
            }
            if (data.hasOwnProperty('h')) {
                obj['h'] = ApiClient.convertToType(data['h'], 'String');
            }
            if (data.hasOwnProperty('g')) {
                obj['g'] = ApiClient.convertToType(data['g'], 'String');
            }
            if (data.hasOwnProperty('u')) {
                obj['u'] = ApiClient.convertToType(data['u'], 'String');
            }
            if (data.hasOwnProperty('v')) {
                obj['v'] = ApiClient.convertToType(data['v'], 'String');
            }
            if (data.hasOwnProperty('condition')) {
                obj['condition'] = ApiClient.convertToType(data['condition'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Sigma opCode
 * @member {Number} op
 */
SigmaBoolean.prototype['op'] = undefined;

/**
 * Base16-encoded bytes
 * @member {String} h
 */
SigmaBoolean.prototype['h'] = undefined;

/**
 * Base16-encoded bytes
 * @member {String} g
 */
SigmaBoolean.prototype['g'] = undefined;

/**
 * Base16-encoded bytes
 * @member {String} u
 */
SigmaBoolean.prototype['u'] = undefined;

/**
 * Base16-encoded bytes
 * @member {String} v
 */
SigmaBoolean.prototype['v'] = undefined;

/**
 * @member {Boolean} condition
 */
SigmaBoolean.prototype['condition'] = undefined;






export default SigmaBoolean;

