/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SourceHolder model module.
 * @module model/SourceHolder
 * @version 4.0.14
 */
class SourceHolder {
    /**
     * Constructs a new <code>SourceHolder</code>.
     * @alias module:model/SourceHolder
     * @param source {String} Sigma source to be compiled
     */
    constructor(source) { 
        
        SourceHolder.initialize(this, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, source) { 
        obj['source'] = source;
    }

    /**
     * Constructs a <code>SourceHolder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceHolder} obj Optional instance to populate.
     * @return {module:model/SourceHolder} The populated <code>SourceHolder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceHolder();

            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Sigma source to be compiled
 * @member {String} source
 */
SourceHolder.prototype['source'] = undefined;






export default SourceHolder;

