/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DhtSecret from './DhtSecret';

/**
 * The TransactionSigningRequestSecrets model module.
 * @module model/TransactionSigningRequestSecrets
 * @version 4.0.14
 */
class TransactionSigningRequestSecrets {
    /**
     * Constructs a new <code>TransactionSigningRequestSecrets</code>.
     * Secrets used for signing
     * @alias module:model/TransactionSigningRequestSecrets
     */
    constructor() { 
        
        TransactionSigningRequestSecrets.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionSigningRequestSecrets</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionSigningRequestSecrets} obj Optional instance to populate.
     * @return {module:model/TransactionSigningRequestSecrets} The populated <code>TransactionSigningRequestSecrets</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionSigningRequestSecrets();

            if (data.hasOwnProperty('dlog')) {
                obj['dlog'] = ApiClient.convertToType(data['dlog'], ['String']);
            }
            if (data.hasOwnProperty('dht')) {
                obj['dht'] = ApiClient.convertToType(data['dht'], [DhtSecret]);
            }
        }
        return obj;
    }


}

/**
 * Sequence of secret exponents (DLOG secrets)
 * @member {Array.<String>} dlog
 */
TransactionSigningRequestSecrets.prototype['dlog'] = undefined;

/**
 * Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)
 * @member {Array.<module:model/DhtSecret>} dht
 */
TransactionSigningRequestSecrets.prototype['dht'] = undefined;






export default TransactionSigningRequestSecrets;

