/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WalletUnlockBody model module.
 * @module model/WalletUnlockBody
 * @version 4.0.14
 */
class WalletUnlockBody {
    /**
     * Constructs a new <code>WalletUnlockBody</code>.
     * @alias module:model/WalletUnlockBody
     * @param pass {String} Password to decrypt wallet file with
     */
    constructor(pass) { 
        
        WalletUnlockBody.initialize(this, pass);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pass) { 
        obj['pass'] = pass;
    }

    /**
     * Constructs a <code>WalletUnlockBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WalletUnlockBody} obj Optional instance to populate.
     * @return {module:model/WalletUnlockBody} The populated <code>WalletUnlockBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletUnlockBody();

            if (data.hasOwnProperty('pass')) {
                obj['pass'] = ApiClient.convertToType(data['pass'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Password to decrypt wallet file with
 * @member {String} pass
 */
WalletUnlockBody.prototype['pass'] = undefined;






export default WalletUnlockBody;

