/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WalletRestoreBody model module.
 * @module model/WalletRestoreBody
 * @version 4.0.14
 */
class WalletRestoreBody {
    /**
     * Constructs a new <code>WalletRestoreBody</code>.
     * @alias module:model/WalletRestoreBody
     * @param pass {String} Password to encrypt wallet file with
     * @param mnemonic {String} Mnemonic seed
     */
    constructor(pass, mnemonic) { 
        
        WalletRestoreBody.initialize(this, pass, mnemonic);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pass, mnemonic) { 
        obj['pass'] = pass;
        obj['mnemonic'] = mnemonic;
    }

    /**
     * Constructs a <code>WalletRestoreBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WalletRestoreBody} obj Optional instance to populate.
     * @return {module:model/WalletRestoreBody} The populated <code>WalletRestoreBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletRestoreBody();

            if (data.hasOwnProperty('pass')) {
                obj['pass'] = ApiClient.convertToType(data['pass'], 'String');
            }
            if (data.hasOwnProperty('mnemonic')) {
                obj['mnemonic'] = ApiClient.convertToType(data['mnemonic'], 'String');
            }
            if (data.hasOwnProperty('mnemonicPass')) {
                obj['mnemonicPass'] = ApiClient.convertToType(data['mnemonicPass'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Password to encrypt wallet file with
 * @member {String} pass
 */
WalletRestoreBody.prototype['pass'] = undefined;

/**
 * Mnemonic seed
 * @member {String} mnemonic
 */
WalletRestoreBody.prototype['mnemonic'] = undefined;

/**
 * Optional pass to password-protect mnemonic seed
 * @member {String} mnemonicPass
 */
WalletRestoreBody.prototype['mnemonicPass'] = undefined;






export default WalletRestoreBody;

