/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ErgoNodeApi);
  }
}(this, function(expect, ErgoNodeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ErgoNodeApi.BlockHeader();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlockHeader', function() {
    it('should create an instance of BlockHeader', function() {
      // uncomment below and update the code to test BlockHeader
      //var instane = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be.a(ErgoNodeApi.BlockHeader);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property adProofsRoot (base name: "adProofsRoot")', function() {
      // uncomment below and update the code to test the property adProofsRoot
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property stateRoot (base name: "stateRoot")', function() {
      // uncomment below and update the code to test the property stateRoot
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property transactionsRoot (base name: "transactionsRoot")', function() {
      // uncomment below and update the code to test the property transactionsRoot
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property nBits (base name: "nBits")', function() {
      // uncomment below and update the code to test the property nBits
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property extensionHash (base name: "extensionHash")', function() {
      // uncomment below and update the code to test the property extensionHash
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property powSolutions (base name: "powSolutions")', function() {
      // uncomment below and update the code to test the property powSolutions
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property difficulty (base name: "difficulty")', function() {
      // uncomment below and update the code to test the property difficulty
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parentId")', function() {
      // uncomment below and update the code to test the property parentId
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property votes (base name: "votes")', function() {
      // uncomment below and update the code to test the property votes
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property extensionId (base name: "extensionId")', function() {
      // uncomment below and update the code to test the property extensionId
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property transactionsId (base name: "transactionsId")', function() {
      // uncomment below and update the code to test the property transactionsId
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

    it('should have the property adProofsId (base name: "adProofsId")', function() {
      // uncomment below and update the code to test the property adProofsId
      //var instance = new ErgoNodeApi.BlockHeader();
      //expect(instance).to.be();
    });

  });

}));
