/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ErgoNodeApi);
  }
}(this, function(expect, ErgoNodeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ErgoNodeApi.ErgoTransactionOutput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ErgoTransactionOutput', function() {
    it('should create an instance of ErgoTransactionOutput', function() {
      // uncomment below and update the code to test ErgoTransactionOutput
      //var instane = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be.a(ErgoNodeApi.ErgoTransactionOutput);
    });

    it('should have the property boxId (base name: "boxId")', function() {
      // uncomment below and update the code to test the property boxId
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property ergoTree (base name: "ergoTree")', function() {
      // uncomment below and update the code to test the property ergoTree
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property creationHeight (base name: "creationHeight")', function() {
      // uncomment below and update the code to test the property creationHeight
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property assets (base name: "assets")', function() {
      // uncomment below and update the code to test the property assets
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property additionalRegisters (base name: "additionalRegisters")', function() {
      // uncomment below and update the code to test the property additionalRegisters
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new ErgoNodeApi.ErgoTransactionOutput();
      //expect(instance).to.be();
    });

  });

}));
