/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ErgoNodeApi);
  }
}(this, function(expect, ErgoNodeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ErgoNodeApi.ErgoLikeContext();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ErgoLikeContext', function() {
    it('should create an instance of ErgoLikeContext', function() {
      // uncomment below and update the code to test ErgoLikeContext
      //var instane = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be.a(ErgoNodeApi.ErgoLikeContext);
    });

    it('should have the property lastBlockUtxoRoot (base name: "lastBlockUtxoRoot")', function() {
      // uncomment below and update the code to test the property lastBlockUtxoRoot
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property headers (base name: "headers")', function() {
      // uncomment below and update the code to test the property headers
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property preHeader (base name: "preHeader")', function() {
      // uncomment below and update the code to test the property preHeader
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property dataBoxes (base name: "dataBoxes")', function() {
      // uncomment below and update the code to test the property dataBoxes
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property boxesToSpend (base name: "boxesToSpend")', function() {
      // uncomment below and update the code to test the property boxesToSpend
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property spendingTransaction (base name: "spendingTransaction")', function() {
      // uncomment below and update the code to test the property spendingTransaction
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property selfIndex (base name: "selfIndex")', function() {
      // uncomment below and update the code to test the property selfIndex
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property extension (base name: "extension")', function() {
      // uncomment below and update the code to test the property extension
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property validationSettings (base name: "validationSettings")', function() {
      // uncomment below and update the code to test the property validationSettings
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property costLimit (base name: "costLimit")', function() {
      // uncomment below and update the code to test the property costLimit
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

    it('should have the property initCost (base name: "initCost")', function() {
      // uncomment below and update the code to test the property initCost
      //var instance = new ErgoNodeApi.ErgoLikeContext();
      //expect(instance).to.be();
    });

  });

}));
