/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ErgoNodeApi);
  }
}(this, function(expect, ErgoNodeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ErgoNodeApi.Parameters();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Parameters', function() {
    it('should create an instance of Parameters', function() {
      // uncomment below and update the code to test Parameters
      //var instane = new ErgoNodeApi.Parameters();
      //expect(instance).to.be.a(ErgoNodeApi.Parameters);
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property storageFeeFactor (base name: "storageFeeFactor")', function() {
      // uncomment below and update the code to test the property storageFeeFactor
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property minValuePerByte (base name: "minValuePerByte")', function() {
      // uncomment below and update the code to test the property minValuePerByte
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property maxBlockSize (base name: "maxBlockSize")', function() {
      // uncomment below and update the code to test the property maxBlockSize
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property maxBlockCost (base name: "maxBlockCost")', function() {
      // uncomment below and update the code to test the property maxBlockCost
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property blockVersion (base name: "blockVersion")', function() {
      // uncomment below and update the code to test the property blockVersion
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property tokenAccessCost (base name: "tokenAccessCost")', function() {
      // uncomment below and update the code to test the property tokenAccessCost
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property inputCost (base name: "inputCost")', function() {
      // uncomment below and update the code to test the property inputCost
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property dataInputCost (base name: "dataInputCost")', function() {
      // uncomment below and update the code to test the property dataInputCost
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

    it('should have the property outputCost (base name: "outputCost")', function() {
      // uncomment below and update the code to test the property outputCost
      //var instance = new ErgoNodeApi.Parameters();
      //expect(instance).to.be();
    });

  });

}));
