/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddressHolder from './model/AddressHolder';
import AddressValidity from './model/AddressValidity';
import AndPredicate from './model/AndPredicate';
import AndPredicateAllOf from './model/AndPredicateAllOf';
import ApiError from './model/ApiError';
import Asset from './model/Asset';
import AssetIssueRequest from './model/AssetIssueRequest';
import AvlTreeData from './model/AvlTreeData';
import BalancesSnapshot from './model/BalancesSnapshot';
import BlacklistedPeers from './model/BlacklistedPeers';
import BlockADProofs from './model/BlockADProofs';
import BlockHeader from './model/BlockHeader';
import BlockHeaderWithoutPow from './model/BlockHeaderWithoutPow';
import BlockTransactions from './model/BlockTransactions';
import CandidateBlock from './model/CandidateBlock';
import Commitment from './model/Commitment';
import CommitmentWithSecret from './model/CommitmentWithSecret';
import ContainsAssetPredicate from './model/ContainsAssetPredicate';
import ContainsAssetPredicateAllOf from './model/ContainsAssetPredicateAllOf';
import ContainsPredicate from './model/ContainsPredicate';
import ContainsPredicateAllOf from './model/ContainsPredicateAllOf';
import CryptoResult from './model/CryptoResult';
import DhtSecret from './model/DhtSecret';
import DlogCommitment from './model/DlogCommitment';
import EmissionInfo from './model/EmissionInfo';
import EqualsPredicate from './model/EqualsPredicate';
import ErgoLikeContext from './model/ErgoLikeContext';
import ErgoLikeTransaction from './model/ErgoLikeTransaction';
import ErgoTransaction from './model/ErgoTransaction';
import ErgoTransactionDataInput from './model/ErgoTransactionDataInput';
import ErgoTransactionInput from './model/ErgoTransactionInput';
import ErgoTransactionOutput from './model/ErgoTransactionOutput';
import ErgoTransactionUnsignedInput from './model/ErgoTransactionUnsignedInput';
import ExecuteScript from './model/ExecuteScript';
import Extension from './model/Extension';
import FeeHistogramBin from './model/FeeHistogramBin';
import FullBlock from './model/FullBlock';
import GenerateCommitmentsRequest from './model/GenerateCommitmentsRequest';
import GenerateCommitmentsRequestSecrets from './model/GenerateCommitmentsRequestSecrets';
import HintExtractionRequest from './model/HintExtractionRequest';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import MerkleProof from './model/MerkleProof';
import NipopowProof from './model/NipopowProof';
import NodeInfo from './model/NodeInfo';
import OrPredicate from './model/OrPredicate';
import Parameters from './model/Parameters';
import PaymentRequest from './model/PaymentRequest';
import Peer from './model/Peer';
import PeersStatus from './model/PeersStatus';
import PopowHeader from './model/PopowHeader';
import PowSolutions from './model/PowSolutions';
import PreHeader from './model/PreHeader';
import ProofOfUpcomingTransactions from './model/ProofOfUpcomingTransactions';
import RequestsHolder from './model/RequestsHolder';
import Scan from './model/Scan';
import ScanId from './model/ScanId';
import ScanIdBoxId from './model/ScanIdBoxId';
import ScanIdsBox from './model/ScanIdsBox';
import ScanRequest from './model/ScanRequest';
import ScanningPredicate from './model/ScanningPredicate';
import SecretProven from './model/SecretProven';
import SerializedBox from './model/SerializedBox';
import SigmaBoolean from './model/SigmaBoolean';
import SigmaBooleanAndPredicate from './model/SigmaBooleanAndPredicate';
import SigmaBooleanAndPredicateAllOf from './model/SigmaBooleanAndPredicateAllOf';
import SigmaBooleanOrPredicate from './model/SigmaBooleanOrPredicate';
import SigmaBooleanThresholdPredicate from './model/SigmaBooleanThresholdPredicate';
import SigmaHeader from './model/SigmaHeader';
import SourceHolder from './model/SourceHolder';
import SpendingProof from './model/SpendingProof';
import TransactionHintsBag from './model/TransactionHintsBag';
import TransactionSigningRequest from './model/TransactionSigningRequest';
import TransactionSigningRequestSecrets from './model/TransactionSigningRequestSecrets';
import UnsignedErgoTransaction from './model/UnsignedErgoTransaction';
import WalletBox from './model/WalletBox';
import WalletCheckBody from './model/WalletCheckBody';
import WalletDeriveKeyBody from './model/WalletDeriveKeyBody';
import WalletInitBody from './model/WalletInitBody';
import WalletRestoreBody from './model/WalletRestoreBody';
import WalletTransaction from './model/WalletTransaction';
import WalletUnlockBody from './model/WalletUnlockBody';
import WalletUpdateChangeAddressBody from './model/WalletUpdateChangeAddressBody';
import WorkMessage from './model/WorkMessage';
import BlocksApi from './api/BlocksApi';
import InfoApi from './api/InfoApi';
import MiningApi from './api/MiningApi';
import NipopowApi from './api/NipopowApi';
import NodeApi from './api/NodeApi';
import PeersApi from './api/PeersApi';
import ScanApi from './api/ScanApi';
import ScriptApi from './api/ScriptApi';
import TransactionsApi from './api/TransactionsApi';
import UtilsApi from './api/UtilsApi';
import UtxoApi from './api/UtxoApi';
import WalletApi from './api/WalletApi';


/**
* API_docs_for_Ergo_Node__Models_are_shared_between_all_Ergo_products.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ErgoNodeApi = require('index'); // See note below*.
* var xxxSvc = new ErgoNodeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ErgoNodeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ErgoNodeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ErgoNodeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.14
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddressHolder model constructor.
     * @property {module:model/AddressHolder}
     */
    AddressHolder,

    /**
     * The AddressValidity model constructor.
     * @property {module:model/AddressValidity}
     */
    AddressValidity,

    /**
     * The AndPredicate model constructor.
     * @property {module:model/AndPredicate}
     */
    AndPredicate,

    /**
     * The AndPredicateAllOf model constructor.
     * @property {module:model/AndPredicateAllOf}
     */
    AndPredicateAllOf,

    /**
     * The ApiError model constructor.
     * @property {module:model/ApiError}
     */
    ApiError,

    /**
     * The Asset model constructor.
     * @property {module:model/Asset}
     */
    Asset,

    /**
     * The AssetIssueRequest model constructor.
     * @property {module:model/AssetIssueRequest}
     */
    AssetIssueRequest,

    /**
     * The AvlTreeData model constructor.
     * @property {module:model/AvlTreeData}
     */
    AvlTreeData,

    /**
     * The BalancesSnapshot model constructor.
     * @property {module:model/BalancesSnapshot}
     */
    BalancesSnapshot,

    /**
     * The BlacklistedPeers model constructor.
     * @property {module:model/BlacklistedPeers}
     */
    BlacklistedPeers,

    /**
     * The BlockADProofs model constructor.
     * @property {module:model/BlockADProofs}
     */
    BlockADProofs,

    /**
     * The BlockHeader model constructor.
     * @property {module:model/BlockHeader}
     */
    BlockHeader,

    /**
     * The BlockHeaderWithoutPow model constructor.
     * @property {module:model/BlockHeaderWithoutPow}
     */
    BlockHeaderWithoutPow,

    /**
     * The BlockTransactions model constructor.
     * @property {module:model/BlockTransactions}
     */
    BlockTransactions,

    /**
     * The CandidateBlock model constructor.
     * @property {module:model/CandidateBlock}
     */
    CandidateBlock,

    /**
     * The Commitment model constructor.
     * @property {module:model/Commitment}
     */
    Commitment,

    /**
     * The CommitmentWithSecret model constructor.
     * @property {module:model/CommitmentWithSecret}
     */
    CommitmentWithSecret,

    /**
     * The ContainsAssetPredicate model constructor.
     * @property {module:model/ContainsAssetPredicate}
     */
    ContainsAssetPredicate,

    /**
     * The ContainsAssetPredicateAllOf model constructor.
     * @property {module:model/ContainsAssetPredicateAllOf}
     */
    ContainsAssetPredicateAllOf,

    /**
     * The ContainsPredicate model constructor.
     * @property {module:model/ContainsPredicate}
     */
    ContainsPredicate,

    /**
     * The ContainsPredicateAllOf model constructor.
     * @property {module:model/ContainsPredicateAllOf}
     */
    ContainsPredicateAllOf,

    /**
     * The CryptoResult model constructor.
     * @property {module:model/CryptoResult}
     */
    CryptoResult,

    /**
     * The DhtSecret model constructor.
     * @property {module:model/DhtSecret}
     */
    DhtSecret,

    /**
     * The DlogCommitment model constructor.
     * @property {module:model/DlogCommitment}
     */
    DlogCommitment,

    /**
     * The EmissionInfo model constructor.
     * @property {module:model/EmissionInfo}
     */
    EmissionInfo,

    /**
     * The EqualsPredicate model constructor.
     * @property {module:model/EqualsPredicate}
     */
    EqualsPredicate,

    /**
     * The ErgoLikeContext model constructor.
     * @property {module:model/ErgoLikeContext}
     */
    ErgoLikeContext,

    /**
     * The ErgoLikeTransaction model constructor.
     * @property {module:model/ErgoLikeTransaction}
     */
    ErgoLikeTransaction,

    /**
     * The ErgoTransaction model constructor.
     * @property {module:model/ErgoTransaction}
     */
    ErgoTransaction,

    /**
     * The ErgoTransactionDataInput model constructor.
     * @property {module:model/ErgoTransactionDataInput}
     */
    ErgoTransactionDataInput,

    /**
     * The ErgoTransactionInput model constructor.
     * @property {module:model/ErgoTransactionInput}
     */
    ErgoTransactionInput,

    /**
     * The ErgoTransactionOutput model constructor.
     * @property {module:model/ErgoTransactionOutput}
     */
    ErgoTransactionOutput,

    /**
     * The ErgoTransactionUnsignedInput model constructor.
     * @property {module:model/ErgoTransactionUnsignedInput}
     */
    ErgoTransactionUnsignedInput,

    /**
     * The ExecuteScript model constructor.
     * @property {module:model/ExecuteScript}
     */
    ExecuteScript,

    /**
     * The Extension model constructor.
     * @property {module:model/Extension}
     */
    Extension,

    /**
     * The FeeHistogramBin model constructor.
     * @property {module:model/FeeHistogramBin}
     */
    FeeHistogramBin,

    /**
     * The FullBlock model constructor.
     * @property {module:model/FullBlock}
     */
    FullBlock,

    /**
     * The GenerateCommitmentsRequest model constructor.
     * @property {module:model/GenerateCommitmentsRequest}
     */
    GenerateCommitmentsRequest,

    /**
     * The GenerateCommitmentsRequestSecrets model constructor.
     * @property {module:model/GenerateCommitmentsRequestSecrets}
     */
    GenerateCommitmentsRequestSecrets,

    /**
     * The HintExtractionRequest model constructor.
     * @property {module:model/HintExtractionRequest}
     */
    HintExtractionRequest,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The MerkleProof model constructor.
     * @property {module:model/MerkleProof}
     */
    MerkleProof,

    /**
     * The NipopowProof model constructor.
     * @property {module:model/NipopowProof}
     */
    NipopowProof,

    /**
     * The NodeInfo model constructor.
     * @property {module:model/NodeInfo}
     */
    NodeInfo,

    /**
     * The OrPredicate model constructor.
     * @property {module:model/OrPredicate}
     */
    OrPredicate,

    /**
     * The Parameters model constructor.
     * @property {module:model/Parameters}
     */
    Parameters,

    /**
     * The PaymentRequest model constructor.
     * @property {module:model/PaymentRequest}
     */
    PaymentRequest,

    /**
     * The Peer model constructor.
     * @property {module:model/Peer}
     */
    Peer,

    /**
     * The PeersStatus model constructor.
     * @property {module:model/PeersStatus}
     */
    PeersStatus,

    /**
     * The PopowHeader model constructor.
     * @property {module:model/PopowHeader}
     */
    PopowHeader,

    /**
     * The PowSolutions model constructor.
     * @property {module:model/PowSolutions}
     */
    PowSolutions,

    /**
     * The PreHeader model constructor.
     * @property {module:model/PreHeader}
     */
    PreHeader,

    /**
     * The ProofOfUpcomingTransactions model constructor.
     * @property {module:model/ProofOfUpcomingTransactions}
     */
    ProofOfUpcomingTransactions,

    /**
     * The RequestsHolder model constructor.
     * @property {module:model/RequestsHolder}
     */
    RequestsHolder,

    /**
     * The Scan model constructor.
     * @property {module:model/Scan}
     */
    Scan,

    /**
     * The ScanId model constructor.
     * @property {module:model/ScanId}
     */
    ScanId,

    /**
     * The ScanIdBoxId model constructor.
     * @property {module:model/ScanIdBoxId}
     */
    ScanIdBoxId,

    /**
     * The ScanIdsBox model constructor.
     * @property {module:model/ScanIdsBox}
     */
    ScanIdsBox,

    /**
     * The ScanRequest model constructor.
     * @property {module:model/ScanRequest}
     */
    ScanRequest,

    /**
     * The ScanningPredicate model constructor.
     * @property {module:model/ScanningPredicate}
     */
    ScanningPredicate,

    /**
     * The SecretProven model constructor.
     * @property {module:model/SecretProven}
     */
    SecretProven,

    /**
     * The SerializedBox model constructor.
     * @property {module:model/SerializedBox}
     */
    SerializedBox,

    /**
     * The SigmaBoolean model constructor.
     * @property {module:model/SigmaBoolean}
     */
    SigmaBoolean,

    /**
     * The SigmaBooleanAndPredicate model constructor.
     * @property {module:model/SigmaBooleanAndPredicate}
     */
    SigmaBooleanAndPredicate,

    /**
     * The SigmaBooleanAndPredicateAllOf model constructor.
     * @property {module:model/SigmaBooleanAndPredicateAllOf}
     */
    SigmaBooleanAndPredicateAllOf,

    /**
     * The SigmaBooleanOrPredicate model constructor.
     * @property {module:model/SigmaBooleanOrPredicate}
     */
    SigmaBooleanOrPredicate,

    /**
     * The SigmaBooleanThresholdPredicate model constructor.
     * @property {module:model/SigmaBooleanThresholdPredicate}
     */
    SigmaBooleanThresholdPredicate,

    /**
     * The SigmaHeader model constructor.
     * @property {module:model/SigmaHeader}
     */
    SigmaHeader,

    /**
     * The SourceHolder model constructor.
     * @property {module:model/SourceHolder}
     */
    SourceHolder,

    /**
     * The SpendingProof model constructor.
     * @property {module:model/SpendingProof}
     */
    SpendingProof,

    /**
     * The TransactionHintsBag model constructor.
     * @property {module:model/TransactionHintsBag}
     */
    TransactionHintsBag,

    /**
     * The TransactionSigningRequest model constructor.
     * @property {module:model/TransactionSigningRequest}
     */
    TransactionSigningRequest,

    /**
     * The TransactionSigningRequestSecrets model constructor.
     * @property {module:model/TransactionSigningRequestSecrets}
     */
    TransactionSigningRequestSecrets,

    /**
     * The UnsignedErgoTransaction model constructor.
     * @property {module:model/UnsignedErgoTransaction}
     */
    UnsignedErgoTransaction,

    /**
     * The WalletBox model constructor.
     * @property {module:model/WalletBox}
     */
    WalletBox,

    /**
     * The WalletCheckBody model constructor.
     * @property {module:model/WalletCheckBody}
     */
    WalletCheckBody,

    /**
     * The WalletDeriveKeyBody model constructor.
     * @property {module:model/WalletDeriveKeyBody}
     */
    WalletDeriveKeyBody,

    /**
     * The WalletInitBody model constructor.
     * @property {module:model/WalletInitBody}
     */
    WalletInitBody,

    /**
     * The WalletRestoreBody model constructor.
     * @property {module:model/WalletRestoreBody}
     */
    WalletRestoreBody,

    /**
     * The WalletTransaction model constructor.
     * @property {module:model/WalletTransaction}
     */
    WalletTransaction,

    /**
     * The WalletUnlockBody model constructor.
     * @property {module:model/WalletUnlockBody}
     */
    WalletUnlockBody,

    /**
     * The WalletUpdateChangeAddressBody model constructor.
     * @property {module:model/WalletUpdateChangeAddressBody}
     */
    WalletUpdateChangeAddressBody,

    /**
     * The WorkMessage model constructor.
     * @property {module:model/WorkMessage}
     */
    WorkMessage,

    /**
    * The BlocksApi service constructor.
    * @property {module:api/BlocksApi}
    */
    BlocksApi,

    /**
    * The InfoApi service constructor.
    * @property {module:api/InfoApi}
    */
    InfoApi,

    /**
    * The MiningApi service constructor.
    * @property {module:api/MiningApi}
    */
    MiningApi,

    /**
    * The NipopowApi service constructor.
    * @property {module:api/NipopowApi}
    */
    NipopowApi,

    /**
    * The NodeApi service constructor.
    * @property {module:api/NodeApi}
    */
    NodeApi,

    /**
    * The PeersApi service constructor.
    * @property {module:api/PeersApi}
    */
    PeersApi,

    /**
    * The ScanApi service constructor.
    * @property {module:api/ScanApi}
    */
    ScanApi,

    /**
    * The ScriptApi service constructor.
    * @property {module:api/ScriptApi}
    */
    ScriptApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi,

    /**
    * The UtilsApi service constructor.
    * @property {module:api/UtilsApi}
    */
    UtilsApi,

    /**
    * The UtxoApi service constructor.
    * @property {module:api/UtxoApi}
    */
    UtxoApi,

    /**
    * The WalletApi service constructor.
    * @property {module:api/WalletApi}
    */
    WalletApi
};
