/**
 * Ergo Node API
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * The version of the OpenAPI document: 4.0.14
 * Contact: ergoplatform@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ErgoNodeApi);
  }
}(this, function(expect, ErgoNodeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ErgoNodeApi.UtilsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UtilsApi', function() {
    describe('addressToRaw', function() {
      it('should call addressToRaw successfully', function(done) {
        //uncomment below and update the code to test addressToRaw
        //instance.addressToRaw(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('checkAddressValidity', function() {
      it('should call checkAddressValidity successfully', function(done) {
        //uncomment below and update the code to test checkAddressValidity
        //instance.checkAddressValidity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ergoTreeToAddress', function() {
      it('should call ergoTreeToAddress successfully', function(done) {
        //uncomment below and update the code to test ergoTreeToAddress
        //instance.ergoTreeToAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRandomSeed', function() {
      it('should call getRandomSeed successfully', function(done) {
        //uncomment below and update the code to test getRandomSeed
        //instance.getRandomSeed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRandomSeedWithLength', function() {
      it('should call getRandomSeedWithLength successfully', function(done) {
        //uncomment below and update the code to test getRandomSeedWithLength
        //instance.getRandomSeedWithLength(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('hashBlake2b', function() {
      it('should call hashBlake2b successfully', function(done) {
        //uncomment below and update the code to test hashBlake2b
        //instance.hashBlake2b(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rawToAddress', function() {
      it('should call rawToAddress successfully', function(done) {
        //uncomment below and update the code to test rawToAddress
        //instance.rawToAddress(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
